name: Python Benchmark Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up pyenv
      uses: gabrielfalcao/pyenv-action@v14
      
    - name: Install Python versions
      run: |
        pyenv install 3.12
        pyenv install 3.13.0
        pyenv install 3.13.0t
        pyenv global 3.12
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run benchmarks
      run: python benchmark_runner.py
      
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: benchmark_results.txt
