name: Python Benchmark Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install pyenv dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev \
          libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
    
    - name: Install and configure pyenv
      run: |
        curl https://pyenv.run | bash
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
        echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(pyenv init -)"' >> ~/.bashrc
        source ~/.bashrc
        
        # Verify pyenv installation
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        pyenv --version
    
    - name: Install Python versions
      run: |
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        
        # Install Python versions
        pyenv install 3.12.7 || pyenv install 3.12.7 --patch < <(curl -sSL https://raw.githubusercontent.com/python/cpython/3.12/Misc/NEWS.d/3.12.7.rst)
        pyenv install 3.13.0 || pyenv install 3.13.0 --patch < <(curl -sSL https://raw.githubusercontent.com/python/cpython/3.13/Misc/NEWS.d/3.13.0.rst)
        pyenv install 3.13.0t || pyenv install 3.13.0t --patch < <(curl -sSL https://raw.githubusercontent.com/python/cpython/nogil/Misc/NEWS.d/3.13.0.rst)
        
        # Set global Python version
        pyenv global 3.12.7
        python --version
        
    - name: Install dependencies
      run: |
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run benchmarks
      run: |
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        python benchmark_runner.py --profile basic --report-format both
      
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: |
          benchmark_results.json
          benchmark_report.json
